/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.grayhat;

import java.awt.Color;
import java.awt.Desktop;
import java.awt.Toolkit;
import java.net.URI;
import java.util.Map;

/**
 *
 * @author GrayHat
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    String titles[]={
    "C",
    "C#",
    "C++",
    "Java",
    "Perl",
    "PHP",
    "Python 3",
    "Scala"
    };
    String langCodes[]={
    "C",
    "Csharp",
    "Cpp",
    "Java",
    "Perl",
    "Php",
    "Python3",
    "Scala"
    };
    int curLang=0;
    String codes[]={
        "#include <stdio.h>\n\nint main(void){\n\tprintf(\"Hello World\");\n\treturn 0;\n}",
        "using System;\nnamespace HelloWorldApp {\n\tclass Gray {\n\t\tstatic void Main(string[] args) {\n\t\t\tConsole.WriteLine(\"Hello World!\");\n\t\t\tConsole.ReadKey();\n\t\t}\n\t}\n}",
        "#include <iostream.h>\n\nint main(void){\n\tcout << \"Hello World\";\n\treturn 0;\n}",
        "//file will be saved as Main.java. Name main class accordingly\npublic class Main{\n\tpublic static void main(String args[]){\n\t\tSystem.out.println(\"Hello World\");\n\t}\n}",
        "use strict;\nuse warnings;\nprint(\"Hello World\\n\");",
        "<?php\necho \"Hello, world!\";\n?>",
        "print(\"Hello World\")",
        "object Gray\n{\n\tdef main(args: Array[String])\n\t{\n\t\tprintln(\"Hello World!\")\n\t}\n}"
    };
    Loading ob;
    public Main() {
        //URL resource = this.getClass().getResource("/");
        ////System.out.println(resource.getPath());
        initComponents();
//        /ob = new Loading();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NavPanel = new javax.swing.JPanel();
        scalalabel = new javax.swing.JLabel();
        clabel = new javax.swing.JLabel();
        cpplabel = new javax.swing.JLabel();
        csharplabel = new javax.swing.JLabel();
        javalabel = new javax.swing.JLabel();
        perllabel = new javax.swing.JLabel();
        phplabel = new javax.swing.JLabel();
        pythonlabel = new javax.swing.JLabel();
        IOPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        outputArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        inputArea = new javax.swing.JTextArea();
        time = new javax.swing.JLabel();
        memory = new javax.swing.JLabel();
        codePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        codeArea = new javax.swing.JTextArea();
        HeadPanel = new javax.swing.JPanel();
        langlabel = new javax.swing.JLabel();
        run = new javax.swing.JLabel();
        titlelabel = new javax.swing.JLabel();
        logolabel = new javax.swing.JLabel();
        close = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GrayCompiler");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/assets/favicon-32x32.png")));
        setUndecorated(true);
        setOpacity(0.95F);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NavPanel.setBackground(new java.awt.Color(0, 18, 50));
        NavPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scalalabel.setDisplayedMnemonic('S');
        scalalabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scalalabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newIcons/scalaaa.png")));
        scalalabel.setToolTipText("");
        scalalabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scalalabelMouseClicked(evt);
            }
        });
        NavPanel.add(scalalabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 48, 39));

        clabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newIcons/C.png")));
        clabel.setToolTipText("");
        clabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clabelMouseClicked(evt);
            }
        });
        NavPanel.add(clabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 48, 39));

        cpplabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cpplabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newIcons/C++.png")));
        cpplabel.setToolTipText("");
        cpplabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cpplabelMouseClicked(evt);
            }
        });
        NavPanel.add(cpplabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 48, 39));

        csharplabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        csharplabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newIcons/C#.png")));
        csharplabel.setToolTipText("");
        csharplabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                csharplabelMouseClicked(evt);
            }
        });
        NavPanel.add(csharplabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 48, 39));

        javalabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        javalabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newIcons/Java.png")));
        javalabel.setToolTipText("");
        javalabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                javalabelMouseClicked(evt);
            }
        });
        NavPanel.add(javalabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 48, 39));

        perllabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        perllabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newIcons/perlll.png")));
        perllabel.setToolTipText("");
        perllabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                perllabelMouseClicked(evt);
            }
        });
        NavPanel.add(perllabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 48, 39));

        phplabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        phplabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newIcons/PHP.png")));
        phplabel.setToolTipText("");
        phplabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phplabelMouseClicked(evt);
            }
        });
        NavPanel.add(phplabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 48, 39));

        pythonlabel.setDisplayedMnemonic('P');
        pythonlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pythonlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newIcons/Python3.png")));
        pythonlabel.setToolTipText("");
        pythonlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pythonlabelMouseClicked(evt);
            }
        });
        NavPanel.add(pythonlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 48, 39));

        getContentPane().add(NavPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 510));

        IOPanel.setBackground(new java.awt.Color(32, 47, 90));
        IOPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        outputArea.setEditable(false);
        outputArea.setBackground(new java.awt.Color(0, 0, 0));
        outputArea.setColumns(20);
        outputArea.setForeground(new java.awt.Color(51, 255, 102));
        outputArea.setRows(5);
        outputArea.setTabSize(5);
        outputArea.setText("OUTPUT HERE");
        outputArea.setBorder(null);
        outputArea.setFocusable(false);
        jScrollPane2.setViewportView(outputArea);

        IOPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 140));

        inputArea.setBackground(new java.awt.Color(102, 102, 102));
        inputArea.setColumns(20);
        inputArea.setForeground(new java.awt.Color(0, 0, 0));
        inputArea.setRows(5);
        inputArea.setTabSize(5);
        inputArea.setText("INPUT HERE");
        inputArea.setBorder(null);
        jScrollPane3.setViewportView(inputArea);

        IOPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, -1, 140));
        IOPanel.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));
        IOPanel.add(memory, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));

        getContentPane().add(IOPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 740, 160));

        codePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setFocusable(false);

        codeArea.setBackground(new java.awt.Color(60, 63, 65));
        codeArea.setColumns(20);
        codeArea.setForeground(new java.awt.Color(0, 255, 102));
        codeArea.setRows(5);
        codeArea.setTabSize(5);
        codeArea.setText(codes[curLang]);
        codeArea.setBorder(null);
        jScrollPane1.setViewportView(codeArea);

        codePanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 310));

        getContentPane().add(codePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 740, 310));

        HeadPanel.setBackground(new java.awt.Color(255, 255, 255));
        HeadPanel.setOpaque(false);
        HeadPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        langlabel.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        langlabel.setForeground(new java.awt.Color(0, 0, 0));
        langlabel.setText(" - "+titles[curLang]);
        langlabel.setOpaque(true);
        HeadPanel.add(langlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 220, -1));

        run.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        run.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/run32.png")));
        run.setOpaque(true);
        run.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                runMouseClicked(evt);
            }
        });
        HeadPanel.add(run, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 40, 40));

        titlelabel.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        titlelabel.setForeground(new java.awt.Color(0, 0, 0));
        titlelabel.setText("Gray Compiler V1.0");
        titlelabel.setOpaque(true);
        HeadPanel.add(titlelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 0, 220, -1));

        logolabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logolabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/favicon-32x32.png")));
        logolabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logolabel.setOpaque(true);
        logolabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logolabelMouseClicked(evt);
            }
        });
        HeadPanel.add(logolabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        close.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setText("X");
        close.setOpaque(true);
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        HeadPanel.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, -1, -1));

        getContentPane().add(HeadPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 740, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stateChanged(){
        langlabel.setText(" - "+titles[curLang]);
        codeArea.setText(codes[curLang]);
    }
    
    private void scalalabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scalalabelMouseClicked
        ////System.out.println("Scala Clicked");
        curLang=7;
        stateChanged();
    }//GEN-LAST:event_scalalabelMouseClicked

    private void clabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clabelMouseClicked
        ////System.out.println("C Clicked");
        curLang=0;
        stateChanged();
    }//GEN-LAST:event_clabelMouseClicked

    private void cpplabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cpplabelMouseClicked
        //System.out.println("C++ Clicked");
        curLang=2;
        stateChanged();
    }//GEN-LAST:event_cpplabelMouseClicked

    private void csharplabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_csharplabelMouseClicked
        //System.out.println("C# Clicked");
        curLang=1;
        stateChanged();
    }//GEN-LAST:event_csharplabelMouseClicked

    private void javalabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_javalabelMouseClicked
        //System.out.println("Java Clicked");
        curLang=3;
        stateChanged();
    }//GEN-LAST:event_javalabelMouseClicked

    private void perllabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perllabelMouseClicked
        //System.out.println("Perl Clicked");
        curLang=4;
        stateChanged();
    }//GEN-LAST:event_perllabelMouseClicked

    private void phplabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phplabelMouseClicked
        //System.out.println("PHP Clicked");
        curLang=5;
        stateChanged();
    }//GEN-LAST:event_phplabelMouseClicked

    private void pythonlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pythonlabelMouseClicked
        //System.out.println("Python3 Clicked");
        curLang=6;
        stateChanged();
    }//GEN-LAST:event_pythonlabelMouseClicked

    
    private void runMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_runMouseClicked
        //this.setVisible(false);
        //ob.main();
        String thisData[] =new String[3];
        thisData[0]=langCodes[curLang];
        thisData[1]=codeArea.getText();
        thisData[2]=inputArea.getText();
        Backend back = new Backend(thisData[0],thisData[1],thisData[2]);
        Map<String,String> result = back.run();
        for(String key :result.keySet())
        {
            System.out.println(key+":"+result.get(key));
        }
        if(result.containsKey("Error"))
        {
            //loading.setText("");
            return;
        }
        time.setText(result.get("time")+" seconds");
        memory.setText(result.get("memory")+ "MB");
        String output="";
        if(!result.get("cmpError").equals(""))
        {
            output += "Compile Time Error : "+result.get("cmpError")+"\n\n";
        }
        if(!result.get("rntError").equals(""))
        {
            output += "Run Time Error : "+result.get("rntError")+"\n\n";
        }
        output += result.get("output");
        outputArea.setText(output);
        //loading.setText("");
        //ob.exit();
        //this.setVisible(true);
    }//GEN-LAST:event_runMouseClicked

    private void logolabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logolabelMouseClicked
        //System.out.println("Logo Clicked");
        try {
            if (Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.BROWSE)) {
                Desktop.getDesktop().browse(new URI("https://grayhat12.github.io/"));
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_logolabelMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        //System.out.println("Close Clicked");
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        close.setForeground(Color.red);
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        close.setForeground(new Color(187,187,187));
    }//GEN-LAST:event_closeMouseExited

    int xp=0,yp=0;
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xp = evt.getX();
        yp = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        this.setLocation(evt.getXOnScreen() - xp, evt.getYOnScreen() - yp);
    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HeadPanel;
    private javax.swing.JPanel IOPanel;
    private javax.swing.JPanel NavPanel;
    private javax.swing.JLabel clabel;
    private javax.swing.JLabel close;
    private javax.swing.JTextArea codeArea;
    private javax.swing.JPanel codePanel;
    private javax.swing.JLabel cpplabel;
    private javax.swing.JLabel csharplabel;
    private javax.swing.JTextArea inputArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel javalabel;
    private javax.swing.JLabel langlabel;
    private javax.swing.JLabel logolabel;
    private javax.swing.JLabel memory;
    private javax.swing.JTextArea outputArea;
    private javax.swing.JLabel perllabel;
    private javax.swing.JLabel phplabel;
    private javax.swing.JLabel pythonlabel;
    private javax.swing.JLabel run;
    private javax.swing.JLabel scalalabel;
    private javax.swing.JLabel time;
    private javax.swing.JLabel titlelabel;
    // End of variables declaration//GEN-END:variables
}